import { Tenant, TenantUser } from '@/types/tenant';
import { Customer, Supplier, Product, Category, StockTransaction, Account, SaleInvoice, PurchaseOrder, Expense, Payment, JournalEntry } from '@/types/erp';
import { AuditLogEntry } from '@/types/audit';

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'supp-001',
    tenantId: 'tenant-apex-corp',
    name: 'Precision Hydraulics Manufacturing [DEMO SEED DATA]',
    code: 'SUPP-001',
    companyName: 'Precision Hydraulics Mfg Corp',
    email: 'orders@precision-hydraulics.com',
    phone: '+1 (555) 482-3901',
    taxNumber: 'US-901823746',
    openingBalance: 0,
    creditLimit: 75000,
    currentBalance: 8400.0,
    paymentTermsDays: 30,
    status: 'active',
    isDeleted: false,
    address: {
      street: '400 Industrial Parkway',
      city: 'Detroit',
      state: 'MI',
      postalCode: '48201',
      country: 'USA',
    },
    notes: 'Primary OEM supplier for continuous duty hydraulic units. High quality vendor.',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'supp-002',
    tenantId: 'tenant-apex-corp',
    name: 'AeroTech Fasteners & Alloys [DEMO SEED DATA]',
    code: 'SUPP-002',
    companyName: 'AeroTech Fasteners LLC',
    email: 'supply@aerotech-alloys.com',
    phone: '+1 (555) 293-8472',
    taxNumber: 'US-827364519',
    openingBalance: 1200.0,
    creditLimit: 40000,
    currentBalance: 3200.0,
    paymentTermsDays: 45,
    status: 'active',
    isDeleted: false,
    address: {
      street: '88 Metals Blvd',
      city: 'Pittsburgh',
      state: 'PA',
      postalCode: '15201',
      country: 'USA',
    },
    notes: 'Specialized titanium bolts and structural aerospace fasteners.',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'supp-003',
    tenantId: 'tenant-apex-corp',
    name: 'ElectroCore Micro-Sensors [DEMO SEED DATA]',
    code: 'SUPP-003',
    companyName: 'ElectroCore Sensor Solutions Inc.',
    email: 'sales@electrocore-sensors.com',
    phone: '+1 (555) 349-8120',
    taxNumber: 'US-719283401',
    openingBalance: 0,
    creditLimit: 30000,
    currentBalance: 0,
    paymentTermsDays: 30,
    status: 'active',
    isDeleted: false,
    address: {
      street: '120 Silicon Way, Bldg C',
      city: 'San Jose',
      state: 'CA',
      postalCode: '95134',
      country: 'USA',
    },
    notes: 'Telemetry sensor modules and infrared arrays provider.',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'supp-004',
    tenantId: 'tenant-apex-corp',
    name: 'Vanguard Industrial Polymers [DEMO SEED DATA]',
    code: 'SUPP-004',
    companyName: 'Vanguard Polymers & Seals Corp',
    email: 'b2b@vanguardpolymers.com',
    phone: '+1 (555) 912-4029',
    taxNumber: 'US-619284710',
    openingBalance: 0,
    creditLimit: 25000,
    currentBalance: 0,
    paymentTermsDays: 15,
    status: 'inactive',
    isDeleted: false,
    address: {
      street: '55 Chemical Plant Road',
      city: 'Baton Rouge',
      state: 'LA',
      postalCode: '70801',
      country: 'USA',
    },
    notes: 'Account temporarily suspended during warehouse relocation.',
    createdAt: new Date(Date.now() - 100 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'supp-005',
    tenantId: 'tenant-apex-corp',
    name: 'Global Packaging & Crating [DEMO SEED DATA]',
    code: 'SUPP-005',
    companyName: 'Global Packaging Solutions LLC',
    email: 'logistics@globalcrating.net',
    phone: '+1 (555) 601-3829',
    taxNumber: 'US-501928472',
    openingBalance: 450.0,
    creditLimit: 15000,
    currentBalance: 450.0,
    paymentTermsDays: 30,
    status: 'active',
    isDeleted: false,
    address: {
      street: '900 Logistics Circle',
      city: 'Fort Worth',
      state: 'TX',
      postalCode: '76101',
      country: 'USA',
    },
    notes: 'Heavy equipment crating, pallets, and hazardous material enclosures.',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-apex-corp',
    name: 'Apex Global Industries',
    legalName: 'Apex Global Industries LLC',
    code: 'APEX',
    status: 'active',
    isDeleted: false,
    email: 'operations@apex-corp.com',
    phone: '+1 (555) 019-2834',
    address: {
      street: '100 Enterprise Way, Suite 400',
      city: 'Austin',
      state: 'TX',
      postalCode: '78701',
      country: 'USA',
    },
    settings: {
      currency: 'USD',
      currencySymbol: '$',
      fiscalYearStartMonth: 1,
      timezone: 'America/Chicago',
      dateFormat: 'YYYY-MM-DD',
      taxNumber: 'US-892374619',
      enableRealtimeSync: true,
      allowNegativeInventory: false,
    },
    ownerId: 'user-default-admin',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tenant-nexus-tech',
    name: 'Nexus Dynamics',
    legalName: 'Nexus Dynamics Technologies Inc.',
    code: 'NEXUS',
    status: 'active',
    isDeleted: false,
    email: 'admin@nexus-dynamics.io',
    phone: '+1 (555) 482-9011',
    address: {
      street: '450 Innovation Blvd',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94107',
      country: 'USA',
    },
    settings: {
      currency: 'EUR',
      currencySymbol: '€',
      fiscalYearStartMonth: 4,
      timezone: 'America/Los_Angeles',
      dateFormat: 'DD/MM/YYYY',
      taxNumber: 'EU-991204851',
      enableRealtimeSync: true,
      allowNegativeInventory: false,
    },
    ownerId: 'user-default-admin',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    tenantId: 'tenant-apex-corp',
    name: 'Vanguard Aerospace Inc. [DEMO SEED DATA]',
    code: 'CUST-001',
    email: 'procurement@vanguard-aero.com',
    phone: '+1 (555) 123-4567',
    companyName: 'Vanguard Aerospace Inc.',
    taxNumber: 'TX-9938472',
    openingBalance: 0,
    creditLimit: 50000,
    currentBalance: 12450.75,
    status: 'active',
    isDeleted: false,
    address: {
      street: '742 Aviation Parkway',
      city: 'Dallas',
      state: 'TX',
      postalCode: '75201',
      country: 'USA',
    },
    notes: 'Premium commercial client. Net 30 terms. High volume purchases.',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cust-002',
    tenantId: 'tenant-apex-corp',
    name: 'Summit Logistics Ltd. [DEMO SEED DATA]',
    code: 'CUST-002',
    email: 'accounts@summit-logistics.net',
    phone: '+1 (555) 987-6543',
    companyName: 'Summit Logistics Ltd.',
    taxNumber: 'IL-1029384',
    openingBalance: 0,
    creditLimit: 25000,
    currentBalance: 3200.0,
    status: 'active',
    isDeleted: false,
    address: {
      street: '12 Harbor Drive',
      city: 'Chicago',
      state: 'IL',
      postalCode: '60601',
      country: 'USA',
    },
    notes: 'Distribution partner for Midwest region.',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedBy: 'user-default-admin',
    createdBy: 'user-default-admin',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cust-003',
    tenantId: 'tenant-apex-corp',
    name: 'Horizon Retailers Co. [DEMO SEED DATA]',
    code: 'CUST-003',
    email: 'billing@horizon-retail.com',
    phone: '+1 (555) 456-7890',
    companyName: 'Horizon Retailers Co.',
    taxNumber: 'FL-4920194',
    openingBalance: 0,
    creditLimit: 10000,
    currentBalance: 0,
    status: 'inactive',
    isDeleted: false,
    address: {
      street: '88 Ocean Blvd',
      city: 'Miami',
      state: 'FL',
      postalCode: '33101',
      country: 'USA',
    },
    notes: 'Account placed on hold due to seasonal restructure.',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cust-004',
    tenantId: 'tenant-apex-corp',
    name: 'NovaTech Automation Labs [DEMO SEED DATA]',
    code: 'CUST-004',
    email: 'finance@novatech-labs.io',
    phone: '+1 (555) 781-9024',
    companyName: 'NovaTech Automation Laboratories Inc.',
    taxNumber: 'CA-8819203',
    openingBalance: 1500.0,
    creditLimit: 35000,
    currentBalance: 1500.0,
    status: 'active',
    isDeleted: false,
    address: {
      street: '500 Robotics Way',
      city: 'Pasadena',
      state: 'CA',
      postalCode: '91101',
      country: 'USA',
    },
    notes: 'Contract robotics integrator. Standard Net 45 payment cycle.',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cust-005',
    tenantId: 'tenant-apex-corp',
    name: 'Pinnacle Energy Services [DEMO SEED DATA]',
    code: 'CUST-005',
    email: 'payables@pinnacle-energy.com',
    phone: '+1 (555) 349-1182',
    companyName: 'Pinnacle Energy Services LLC',
    taxNumber: 'CO-3918204',
    openingBalance: 0,
    creditLimit: 60000,
    currentBalance: 0,
    status: 'active',
    isDeleted: false,
    address: {
      street: '1400 17th St, Suite 2100',
      city: 'Denver',
      state: 'CO',
      postalCode: '80202',
      country: 'USA',
    },
    notes: 'Renewable and grid infrastructure engineering client.',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cust-006',
    tenantId: 'tenant-nexus-tech',
    name: 'Quantum Softworks Europe [DEMO SEED DATA]',
    code: 'CUST-101',
    email: 'invoices@quantum-softworks.eu',
    phone: '+44 20 7946 0912',
    companyName: 'Quantum Softworks Europe Ltd.',
    taxNumber: 'GB-192837465',
    openingBalance: 0,
    creditLimit: 80000,
    currentBalance: 24500.0,
    status: 'active',
    isDeleted: false,
    address: {
      street: '22 Silicon Way',
      city: 'London',
      state: 'Greater London',
      postalCode: 'EC2A 4NE',
      country: 'UK',
    },
    notes: 'Enterprise SaaS client.',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    tenantId: 'tenant-apex-corp',
    name: 'Industrial Grade Hydraulic Pump H-400',
    sku: 'PUMP-HYD-400',
    barcode: '890123456789',
    category: 'Heavy Machinery',
    unit: 'pcs',
    costPrice: 850.0,
    sellingPrice: 1450.0,
    taxRate: 8.25,
    currentStock: 42,
    minStockAlert: 10,
    maxStockLevel: 100,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300&auto=format&fit=crop&q=80',
    description: 'High-pressure continuous duty hydraulic pump unit.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'prod-002',
    tenantId: 'tenant-apex-corp',
    name: 'Reinforced Carbon Filter Cartridge 20"',
    sku: 'FLTR-CRB-020',
    barcode: '890123456790',
    category: 'Filtration',
    unit: 'box',
    costPrice: 45.0,
    sellingPrice: 89.99,
    taxRate: 8.25,
    currentStock: 120,
    minStockAlert: 25,
    maxStockLevel: 500,
    imageUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=300&auto=format&fit=crop&q=80',
    description: 'Activated carbon multi-layer filtration cartridge.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'prod-003',
    tenantId: 'tenant-apex-corp',
    name: 'Thermal Imaging Sensor Module T-90',
    sku: 'SNSR-THM-090',
    barcode: '890123456791',
    category: 'Electronics',
    unit: 'pcs',
    costPrice: 220.0,
    sellingPrice: 495.0,
    taxRate: 8.25,
    currentStock: 6,
    minStockAlert: 15,
    maxStockLevel: 50,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&auto=format&fit=crop&q=80',
    description: 'Calibrated infrared thermal sensor array for telemetry.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'prod-004',
    tenantId: 'tenant-apex-corp',
    name: 'Legacy Solenoid Valve 1/2" NPT (Discontinued)',
    sku: 'VALV-SLN-050-D',
    barcode: '890123456792',
    category: 'Valves & Fittings',
    unit: 'pcs',
    costPrice: 32.0,
    sellingPrice: 65.0,
    taxRate: 8.25,
    currentStock: 0,
    minStockAlert: 5,
    maxStockLevel: 40,
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=300&auto=format&fit=crop&q=80',
    description: 'Superseded by Rev B. Kept for historical inventory audits.',
    status: 'inactive',
    isDeleted: false,
    createdAt: new Date(Date.now() - 80 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'prod-005',
    tenantId: 'tenant-nexus-tech',
    name: 'Optical Network Transceiver 100G QSFP28',
    sku: 'OPT-QSFP-100G',
    barcode: '789123456001',
    category: 'Networking',
    unit: 'pcs',
    costPrice: 310.0,
    sellingPrice: 580.0,
    taxRate: 20.0,
    currentStock: 85,
    minStockAlert: 20,
    maxStockLevel: 200,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=300&auto=format&fit=crop&q=80',
    description: '100GBASE-LR4 single mode fiber transceiver.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'prod-006',
    tenantId: 'tenant-apex-corp',
    name: 'Precision Titanium Hex Bolt M8x50mm [DEMO SEED DATA]',
    sku: 'BLT-TIT-0850',
    barcode: '890123456793',
    category: 'Heavy Machinery',
    unit: 'box',
    costPrice: 15.0,
    sellingPrice: 35.0,
    taxRate: 8.25,
    currentStock: 80,
    minStockAlert: 20,
    maxStockLevel: 300,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300&auto=format&fit=crop&q=80',
    description: 'High tensile aerospace grade titanium alloy hex fasteners.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'prod-007',
    tenantId: 'tenant-apex-corp',
    name: 'Viton Chemical Resistant O-Ring Pack (100pcs) [DEMO SEED DATA]',
    sku: 'RING-VTN-100',
    barcode: '890123456794',
    category: 'Industrial Polymers',
    unit: 'pack',
    costPrice: 28.0,
    sellingPrice: 62.5,
    taxRate: 8.25,
    currentStock: 50,
    minStockAlert: 15,
    maxStockLevel: 250,
    imageUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=300&auto=format&fit=crop&q=80',
    description: 'Fluorocarbon elastomer sealing rings for high temperature fluid containment.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-001',
    tenantId: 'tenant-apex-corp',
    userId: 'user-default-admin',
    userEmail: 'admin@apex-corp.com',
    userName: 'Chief Administrator',
    action: 'CREATE',
    module: 'Tenants',
    entityId: 'tenant-apex-corp',
    recordId: 'tenant-apex-corp',
    entityName: 'Apex Global Industries',
    description: 'Initialized tenant workspace and master chart of accounts',
    previousValue: null,
    newValue: { name: 'Apex Global Industries', currency: 'USD', country: 'US' },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: new Date(Date.now() - 90 * 86400000).toISOString(),
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'audit-002',
    tenantId: 'tenant-apex-corp',
    userId: 'user-default-admin',
    userEmail: 'admin@apex-corp.com',
    userName: 'Chief Administrator',
    action: 'CREATE',
    module: 'Customers',
    entityId: 'cust-001',
    recordId: 'cust-001',
    entityName: 'Vanguard Aerospace Inc.',
    description: 'Created new master customer account with credit limit $50,000',
    previousValue: null,
    newValue: { code: 'CUST-001', name: 'Vanguard Aerospace Inc.', creditLimit: 50000 },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: new Date(Date.now() - 30 * 86400000).toISOString(),
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'audit-003',
    tenantId: 'tenant-apex-corp',
    userId: 'user-default-admin',
    userEmail: 'admin@apex-corp.com',
    userName: 'Chief Administrator',
    action: 'STATUS_CHANGE',
    module: 'Customers',
    entityId: 'cust-003',
    recordId: 'cust-003',
    entityName: 'Horizon Retailers Co.',
    description: 'Disabled customer account (status set to inactive)',
    previousValue: { status: 'active' },
    newValue: { status: 'inactive' },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'audit-004',
    tenantId: 'tenant-apex-corp',
    userId: 'user-admin-sarah',
    userEmail: 'sarah.admin@apex-corp.com',
    userName: 'Sarah Jenkins',
    action: 'POST',
    module: 'Sales',
    entityId: 'inv-001',
    recordId: 'INV-1001',
    entityName: 'Vanguard Aerospace Inc.',
    description: 'Posted Sales Invoice #INV-1001 for $8,250.00 and decremented stock',
    previousValue: { saleStatus: 'draft', stock: 25 },
    newValue: { saleStatus: 'posted', totalAmount: 8250.0, stock: 17 },
    ipAddress: '192.168.1.105',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    createdBy: 'user-admin-sarah',
    updatedBy: 'user-admin-sarah',
  },
  {
    id: 'audit-005',
    tenantId: 'tenant-apex-corp',
    userId: 'user-default-admin',
    userEmail: 'admin@apex-corp.com',
    userName: 'Chief Administrator',
    action: 'PAYMENT',
    module: 'Payments',
    entityId: 'pay-001',
    recordId: 'RCPT-1001',
    entityName: 'Vanguard Aerospace Inc.',
    description: 'Processed wire receipt payment $5,000.00 towards Invoice #INV-1001',
    previousValue: { customerBalance: 8250.0, bankBalance: 143650.0 },
    newValue: { customerBalance: 3250.0, bankBalance: 148650.0 },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'audit-006',
    tenantId: 'tenant-apex-corp',
    userId: 'user-default-admin',
    userEmail: 'admin@apex-corp.com',
    userName: 'Chief Administrator',
    action: 'STOCK_ADJUSTMENT',
    module: 'Inventory',
    entityId: 'prod-001',
    recordId: 'ADJ-WO-001',
    entityName: 'Industrial Hydraulic Pump H-400',
    description: 'Adjusted physical inventory count after periodic warehouse cycle audit',
    previousValue: { physicalStock: 18 },
    newValue: { physicalStock: 17, adjustmentQty: -1 },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'audit-007',
    tenantId: 'tenant-apex-corp',
    userId: 'user-default-admin',
    userEmail: 'admin@apex-corp.com',
    userName: 'Chief Administrator',
    action: 'CANCEL',
    module: 'Expenses',
    entityId: 'exp-007',
    recordId: 'EXP-3007',
    entityName: 'Speedy Courier Dispatch',
    description: 'Voided duplicate freight expense voucher and posted counter-balancing accounting reversal',
    previousValue: { status: 'posted', amount: 220.0 },
    newValue: { status: 'void', voidReason: 'Duplicate courier invoice' },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    timestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_USERS: TenantUser[] = [
  {
    id: 'user-default-admin',
    tenantId: 'tenant-apex-corp',
    email: 'admin@apex-corp.com',
    displayName: 'Chief Executive Officer',
    role: 'super_admin',
    status: 'active',
    isDeleted: false,
    phone: '+1 (555) 019-2834',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'user-admin-sarah',
    tenantId: 'tenant-apex-corp',
    email: 'sarah.admin@apex-corp.com',
    displayName: 'Sarah Jenkins',
    role: 'admin',
    status: 'active',
    isDeleted: false,
    phone: '+1 (555) 302-8841',
    createdAt: new Date(Date.now() - 75 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'user-default-manager',
    tenantId: 'tenant-apex-corp',
    email: 'operations@apex-corp.com',
    displayName: 'Marcus Vance',
    role: 'manager',
    status: 'active',
    isDeleted: false,
    phone: '+1 (555) 492-1049',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'user-staff-emily',
    tenantId: 'tenant-apex-corp',
    email: 'emily.staff@apex-corp.com',
    displayName: 'Emily Watson',
    role: 'staff',
    status: 'active',
    isDeleted: false,
    phone: '+1 (555) 883-9201',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'user-inactive-alex',
    tenantId: 'tenant-apex-corp',
    email: 'alex.former@apex-corp.com',
    displayName: 'Alex Thorne (Contractor)',
    role: 'staff',
    status: 'inactive',
    isDeleted: false,
    phone: '+1 (555) 774-2910',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'user-staff-zayn',
    tenantId: 'tenant-apex-corp',
    email: 'zayn.inventory@apex-corp.com',
    displayName: 'Zayn Malik (Inventory Lead)',
    role: 'staff',
    status: 'active',
    isDeleted: false,
    phone: '+1 (555) 782-9012',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  // 1. Current Assets (Cash & Bank)
  {
    id: 'acc-001',
    tenantId: 'tenant-apex-corp',
    accountNumber: '1010-BOA-OPERATING',
    accountName: 'Bank of America — Primary Operating',
    type: 'bank',
    accountCategory: 'asset',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 148650.0,
    currentBalance: 148650.0,
    bankName: 'Bank of America',
    bankBranch: 'Austin Downtown',
    isDefault: true,
    status: 'active',
    isDeleted: false,
    description: 'Primary commercial treasury checking account',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-002',
    tenantId: 'tenant-apex-corp',
    accountNumber: '1020-PETTY-CASH',
    accountName: 'Main Office Petty Cash Drawer',
    type: 'cash',
    accountCategory: 'asset',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 5420.5,
    currentBalance: 5420.5,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'On-premises physical till and operational disbursements',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-003',
    tenantId: 'tenant-apex-corp',
    accountNumber: '1030-JPM-COMMERCIAL',
    accountName: 'JPMorgan Chase — Commercial Reserve',
    type: 'bank',
    accountCategory: 'asset',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 85200.0,
    currentBalance: 85200.0,
    bankName: 'JPMorgan Chase Bank',
    bankBranch: 'Austin North Tech Ridge',
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Secondary liquid capital reserve',
    createdAt: new Date(Date.now() - 80 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-004',
    tenantId: 'tenant-apex-corp',
    accountNumber: '1040-MEZN-EXPORT',
    accountName: 'Meezan Bank — Foreign Exchange Escrow',
    type: 'bank',
    accountCategory: 'asset',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 34100.0,
    currentBalance: 34100.0,
    bankName: 'Meezan Bank Ltd.',
    bankBranch: 'Main Boulevard Commercial',
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Import/Export cross-border escrow clearing',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-005',
    tenantId: 'tenant-apex-corp',
    accountNumber: '1050-STRIPE-MERCHANT',
    accountName: 'Stripe Merchant Gateway Clearing',
    type: 'bank',
    accountCategory: 'asset',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 12450.0,
    currentBalance: 12450.0,
    bankName: 'Stripe Payments US',
    bankBranch: 'San Francisco Digital',
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Digital payment gateway settlement holding account',
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // 2. Control Assets
  {
    id: 'acc-1100',
    tenantId: 'tenant-apex-corp',
    accountNumber: '1100-AR-CONTROL',
    accountName: 'Accounts Receivable Control (Trade Debtors)',
    type: 'accounts_receivable',
    accountCategory: 'asset',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Control account tracking all pending customer invoice balances',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-1200',
    tenantId: 'tenant-apex-corp',
    accountNumber: '1200-INV-MERCH',
    accountName: 'Merchandise Inventory Stock Asset',
    type: 'inventory',
    accountCategory: 'asset',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Total real-time inventory assets on hand at wholesale cost',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // 3. Liabilities
  {
    id: 'acc-2010',
    tenantId: 'tenant-apex-corp',
    accountNumber: '2010-AP-CONTROL',
    accountName: 'Accounts Payable Control (Trade Creditors)',
    type: 'accounts_payable',
    accountCategory: 'liability',
    normalBalance: 'credit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Control account tracking outstanding obligations to suppliers',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-2050',
    tenantId: 'tenant-apex-corp',
    accountNumber: '2050-TAX-PAYABLE',
    accountName: 'Sales Tax & VAT Payable',
    type: 'liability',
    accountCategory: 'liability',
    normalBalance: 'credit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Sales tax collected on invoices payable to state authorities',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // 4. Owner Equity
  {
    id: 'acc-3010',
    tenantId: 'tenant-apex-corp',
    accountNumber: '3010-EQUITY-CAPITAL',
    accountName: "Owner's Contributed Capital & Equity",
    type: 'equity',
    accountCategory: 'equity',
    normalBalance: 'credit',
    currency: 'USD',
    openingBalance: 285820.5,
    currentBalance: 285820.5,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Direct capital contributed by founding shareholders',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-3020',
    tenantId: 'tenant-apex-corp',
    accountNumber: '3020-RETAINED-EARNINGS',
    accountName: 'Retained Business Earnings',
    type: 'equity',
    accountCategory: 'equity',
    normalBalance: 'credit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Accumulated net profit retained in business operations',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // 5. Operating Revenue
  {
    id: 'acc-4010',
    tenantId: 'tenant-apex-corp',
    accountNumber: '4010-SALES-REVENUE',
    accountName: 'Commercial Sales Revenue',
    type: 'income',
    accountCategory: 'revenue',
    normalBalance: 'credit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Gross income earned from fulfillment of customer orders',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // 6. Cost of Goods Sold (COGS)
  {
    id: 'acc-5010',
    tenantId: 'tenant-apex-corp',
    accountNumber: '5010-COGS-WHOLESALE',
    accountName: 'Cost of Goods Sold (COGS) — Wholesale',
    type: 'cogs',
    accountCategory: 'cogs',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Acquisition and landed cost of products sold to customers',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // 7. Operating Overhead Expenses
  {
    id: 'acc-6010',
    tenantId: 'tenant-apex-corp',
    accountNumber: '6010-EXP-FACILITY',
    accountName: 'Facility Lease & Warehouse Expenses',
    type: 'expense',
    accountCategory: 'expense',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Rental and leasing of industrial warehouse and physical plants',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-6020',
    tenantId: 'tenant-apex-corp',
    accountNumber: '6020-EXP-CLOUD',
    accountName: 'Cloud Infrastructure & Software SaaS',
    type: 'expense',
    accountCategory: 'expense',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Serverless clusters, hosting, database, and software subscriptions',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-6030',
    tenantId: 'tenant-apex-corp',
    accountNumber: '6030-EXP-LOGISTICS',
    accountName: 'Freight, Logistics & Fuel Expenses',
    type: 'expense',
    accountCategory: 'expense',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Courier delivery, transport freight, and fleet fuels',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-6040',
    tenantId: 'tenant-apex-corp',
    accountNumber: '6040-EXP-MARKETING',
    accountName: 'Advertising & Marketing Campaigns',
    type: 'expense',
    accountCategory: 'expense',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Digital promotions, trade exhibitions, and enterprise lead generation',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-6050',
    tenantId: 'tenant-apex-corp',
    accountNumber: '6050-EXP-UTILITIES',
    accountName: 'Utilities & Industrial Three-Phase Power',
    type: 'expense',
    accountCategory: 'expense',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Electric power, water, and municipal sanitation utilities',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'acc-6060',
    tenantId: 'tenant-apex-corp',
    accountNumber: '6060-EXP-ADMIN',
    accountName: 'Office Stationery & Administration',
    type: 'expense',
    accountCategory: 'expense',
    normalBalance: 'debit',
    currency: 'USD',
    openingBalance: 0,
    currentBalance: 0,
    isDefault: false,
    status: 'active',
    isDeleted: false,
    description: 'Office supplies, printing, paper rolls, and administrative sundries',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_SALES: SaleInvoice[] = [
  {
    id: 'inv-001',
    tenantId: 'tenant-apex-corp',
    invoiceNumber: 'INV-1001',
    customerId: 'cust-001',
    customerName: 'Vanguard Aerospace Inc.',
    date: new Date(Date.now() - 1 * 86400000).toISOString(), // Yesterday (This Week / Month)
    dueDate: new Date(Date.now() + 29 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-001',
        productName: 'Industrial Grade Hydraulic Pump H-400',
        sku: 'PUMP-HYD-400',
        quantity: 4,
        unitPrice: 1450.0,
        costPrice: 850.0,
        taxRate: 8.25,
        subtotal: 5800.0,
        total: 6278.5,
      },
    ],
    subtotal: 5800.0,
    taxAmount: 478.5,
    discountAmount: 0,
    totalAmount: 6278.5,
    paidAmount: 6278.5,
    balanceAmount: 0,
    paymentStatus: 'paid',
    notes: 'Paid via direct wire transfer.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'inv-002',
    tenantId: 'tenant-apex-corp',
    invoiceNumber: 'INV-1002',
    customerId: 'cust-002',
    customerName: 'Summit Logistics Ltd.',
    date: new Date(Date.now() - 3 * 86400000).toISOString(), // This Week / Month
    dueDate: new Date(Date.now() + 27 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-002',
        productName: 'Reinforced Carbon Filter Cartridge 20"',
        sku: 'FLTR-CRB-020',
        quantity: 20,
        unitPrice: 89.99,
        costPrice: 45.0,
        taxRate: 8.25,
        subtotal: 1799.8,
        total: 1948.28,
      },
    ],
    subtotal: 1799.8,
    taxAmount: 148.48,
    discountAmount: 0,
    totalAmount: 1948.28,
    paidAmount: 1000.0,
    balanceAmount: 948.28,
    paymentStatus: 'partial',
    notes: 'Partial payment received on delivery.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'inv-003',
    tenantId: 'tenant-apex-corp',
    invoiceNumber: 'INV-1003',
    customerId: 'cust-001',
    customerName: 'Vanguard Aerospace Inc.',
    date: new Date().toISOString(), // Today
    dueDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-003',
        productName: 'Thermal Imaging Sensor Module T-90',
        sku: 'SNSR-THM-090',
        quantity: 2,
        unitPrice: 495.0,
        costPrice: 220.0,
        taxRate: 8.25,
        subtotal: 990.0,
        total: 1071.68,
      },
    ],
    subtotal: 990.0,
    taxAmount: 81.68,
    discountAmount: 0,
    totalAmount: 1071.68,
    paidAmount: 0,
    balanceAmount: 1071.68,
    paymentStatus: 'unpaid',
    notes: 'Standard Net 30 terms.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'inv-004',
    tenantId: 'tenant-apex-corp',
    invoiceNumber: 'INV-1004',
    customerId: 'cust-003',
    customerName: 'Horizon Retailers Co. [DEMO SEED DATA]',
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 26 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-002',
        productName: 'Reinforced Carbon Filter Cartridge 20"',
        sku: 'FLTR-CRB-020',
        quantity: 30,
        unitPrice: 89.99,
        costPrice: 45.0,
        taxRate: 8.25,
        subtotal: 2699.7,
        total: 2922.43,
      },
    ],
    subtotal: 2699.7,
    taxAmount: 222.73,
    discountAmount: 0,
    totalAmount: 2922.43,
    paidAmount: 2922.43,
    balanceAmount: 0,
    paymentStatus: 'paid',
    notes: 'Paid in full via ACH transfer upon dispatch.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'inv-005',
    tenantId: 'tenant-apex-corp',
    invoiceNumber: 'INV-1005',
    customerId: 'cust-004',
    customerName: 'Quantum Robotics Labs [DEMO SEED DATA]',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 28 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-003',
        productName: 'Thermal Imaging Sensor Module T-90',
        sku: 'SNSR-THM-090',
        quantity: 1,
        unitPrice: 495.0,
        costPrice: 220.0,
        taxRate: 8.25,
        subtotal: 495.0,
        total: 535.84,
      },
    ],
    subtotal: 495.0,
    taxAmount: 40.84,
    discountAmount: 0,
    totalAmount: 535.84,
    paidAmount: 250.0,
    balanceAmount: 285.84,
    paymentStatus: 'partial',
    notes: 'Advance deposit received, balance upon calibration check.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_PURCHASES: PurchaseOrder[] = [
  {
    id: 'po-001',
    tenantId: 'tenant-apex-corp',
    poNumber: 'PO-2001',
    supplierId: 'supp-001',
    supplierName: 'Precision Hydraulics Manufacturing [DEMO SEED DATA]',
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 25 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-001',
        productName: 'Industrial Grade Hydraulic Pump H-400',
        sku: 'PUMP-HYD-400',
        quantity: 5,
        unitCost: 850.0,
        taxRate: 0,
        discountPercent: 0,
        discountAmount: 0,
        subtotal: 4250.0,
        total: 4250.0,
        returnedQuantity: 0,
      },
    ],
    subtotal: 4250.0,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: 4250.0,
    paidAmount: 4250.0,
    balanceAmount: 0,
    paymentStatus: 'paid',
    receiptStatus: 'received',
    purchaseStatus: 'received',
    purchaseType: 'cash',
    paymentMethod: 'cash',
    accountId: 'acc-002',
    accountName: 'Main Office Petty Cash Drawer',
    notes: 'Warehouse batch shipment received in full. Paid in full via cash counter disbursement.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'po-002',
    tenantId: 'tenant-apex-corp',
    poNumber: 'PO-2002',
    supplierId: 'supp-001',
    supplierName: 'Precision Hydraulics Manufacturing [DEMO SEED DATA]',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 27 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-002',
        productName: 'Reinforced Carbon Filter Cartridge 20"',
        sku: 'FLTR-CRB-020',
        quantity: 50,
        unitCost: 45.0,
        taxRate: 0,
        discountPercent: 0,
        discountAmount: 0,
        subtotal: 2250.0,
        total: 2250.0,
        returnedQuantity: 0,
      },
    ],
    subtotal: 2250.0,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: 2250.0,
    paidAmount: 1000.0,
    balanceAmount: 1250.0,
    paymentStatus: 'partial',
    receiptStatus: 'received',
    purchaseStatus: 'received',
    purchaseType: 'partial',
    paymentMethod: 'bank_transfer',
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    notes: 'Partial down-payment executed via wire transfer. Remaining $1,250 payable Net 30.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'po-003',
    tenantId: 'tenant-apex-corp',
    poNumber: 'PO-2003',
    supplierId: 'supp-002',
    supplierName: 'AeroTech Fasteners & Alloys [DEMO SEED DATA]',
    date: new Date(Date.now() - 7 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 23 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-006',
        productName: 'Precision Titanium Hex Bolt M8x50mm [DEMO SEED DATA]',
        sku: 'BLT-TIT-0850',
        quantity: 120,
        unitCost: 15.0,
        taxRate: 0,
        discountPercent: 0,
        discountAmount: 0,
        subtotal: 1800.0,
        total: 1800.0,
        returnedQuantity: 0,
      },
    ],
    subtotal: 1800.0,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: 1800.0,
    paidAmount: 0,
    balanceAmount: 1800.0,
    paymentStatus: 'unpaid',
    receiptStatus: 'received',
    purchaseStatus: 'received',
    purchaseType: 'credit',
    notes: 'Procured 100% on credit (Accounts Payable). 45-day commercial vendor payment terms.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'po-004',
    tenantId: 'tenant-apex-corp',
    poNumber: 'PO-2004',
    supplierId: 'supp-003',
    supplierName: 'ElectroCore Micro-Sensors [DEMO SEED DATA]',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 28 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-003',
        productName: 'Thermal Imaging Sensor Module T-90',
        sku: 'SNSR-THM-090',
        quantity: 10,
        unitCost: 220.0,
        taxRate: 0,
        discountPercent: 10,
        discountAmount: 220.0,
        subtotal: 1980.0,
        total: 1980.0,
        returnedQuantity: 0,
      },
    ],
    subtotal: 2200.0,
    discountAmount: 220.0,
    taxAmount: 0,
    totalAmount: 1980.0,
    paidAmount: 0,
    balanceAmount: 1980.0,
    paymentStatus: 'unpaid',
    receiptStatus: 'pending',
    purchaseStatus: 'draft',
    purchaseType: 'credit',
    notes: 'Draft quotation under procurement review. Inventory and accounts are not yet impacted.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'po-005',
    tenantId: 'tenant-apex-corp',
    poNumber: 'PO-2005',
    supplierId: 'supp-005',
    supplierName: 'Global Packaging & Crating [DEMO SEED DATA]',
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 26 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-001',
        productName: 'Industrial Grade Hydraulic Pump H-400',
        sku: 'PUMP-HYD-400',
        quantity: 8,
        unitCost: 850.0,
        taxRate: 0,
        discountPercent: 0,
        discountAmount: 0,
        subtotal: 6800.0,
        total: 6800.0,
        returnedQuantity: 2,
      },
    ],
    subtotal: 6800.0,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: 6800.0,
    paidAmount: 3400.0,
    balanceAmount: 3400.0,
    paymentStatus: 'partial',
    receiptStatus: 'received',
    purchaseStatus: 'returned',
    purchaseType: 'partial',
    paymentMethod: 'bank_transfer',
    accountId: 'acc-003',
    accountName: 'JPMorgan Chase — Commercial Reserve',
    returnReason: 'Quality inspection failure: 2 units damaged upon freight arrival; debit note claimed.',
    returnDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    notes: '2 units returned for vendor debit credit. Remaining 6 units active in warehouse inventory.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'po-006',
    tenantId: 'tenant-apex-corp',
    poNumber: 'PO-2006',
    supplierId: 'supp-002',
    supplierName: 'AeroTech Fasteners & Alloys [DEMO SEED DATA]',
    date: new Date(Date.now() - 8 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 22 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-006',
        productName: 'Precision Titanium Hex Bolt M8x50mm [DEMO SEED DATA]',
        sku: 'BLT-TIT-0850',
        quantity: 100,
        unitCost: 15.0,
        taxRate: 0,
        discountPercent: 0,
        discountAmount: 0,
        subtotal: 1500.0,
        total: 1500.0,
        returnedQuantity: 0,
      },
    ],
    subtotal: 1500.0,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: 1500.0,
    paidAmount: 0,
    balanceAmount: 1500.0,
    paymentStatus: 'unpaid',
    receiptStatus: 'received',
    purchaseStatus: 'void',
    purchaseType: 'credit',
    voidReason: 'Supplier informed delay exceeding critical production schedule; procurement cancelled and stock reversed.',
    voidDate: new Date(Date.now() - 6 * 86400000).toISOString(),
    notes: 'Order cancelled. Double-entry counter-balancing transactions generated to keep clean audit trails.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'po-007',
    tenantId: 'tenant-apex-corp',
    poNumber: 'PO-2007',
    supplierId: 'supp-004',
    supplierName: 'Vanguard Industrial Polymers [DEMO SEED DATA]',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 29 * 86400000).toISOString(),
    items: [
      {
        productId: 'prod-007',
        productName: 'Viton Chemical Resistant O-Ring Pack (100pcs) [DEMO SEED DATA]',
        sku: 'RING-VTN-100',
        quantity: 15,
        unitCost: 28.0,
        taxRate: 0,
        discountPercent: 0,
        discountAmount: 0,
        subtotal: 420.0,
        total: 420.0,
        returnedQuantity: 0,
      },
    ],
    subtotal: 420.0,
    discountAmount: 0,
    taxAmount: 0,
    totalAmount: 420.0,
    paidAmount: 420.0,
    balanceAmount: 0,
    paymentStatus: 'paid',
    receiptStatus: 'pending',
    purchaseStatus: 'received',
    purchaseType: 'bank',
    paymentMethod: 'bank_transfer',
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    notes: 'In-transit shipment from Louisiana plant. Ready for warehouse receipt scanning when delivered.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    tenantId: 'tenant-apex-corp',
    expenseNumber: 'EXP-3001',
    category: 'Facility & Rent',
    date: new Date(Date.now() - 2 * 86400000).toISOString(), // This Week / Month
    amount: 1850.0,
    taxAmount: 0,
    totalAmount: 1850.0,
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'bank_transfer',
    vendor: 'Austin Industrial Park Holdings',
    description: 'Monthly warehouse facility lease installment',
    expenseStatus: 'posted',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'exp-002',
    tenantId: 'tenant-apex-corp',
    expenseNumber: 'EXP-3002',
    category: 'Cloud & Infrastructure',
    date: new Date().toISOString(), // Today
    amount: 420.0,
    taxAmount: 34.65,
    totalAmount: 454.65,
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'credit_card',
    vendor: 'Google Cloud Platform',
    description: 'Production Firebase and serverless cloud clusters',
    expenseStatus: 'posted',
    status: 'active',
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'exp-003',
    tenantId: 'tenant-apex-corp',
    expenseNumber: 'EXP-3003',
    category: 'Logistics & Fuel',
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    amount: 310.0,
    taxAmount: 0,
    totalAmount: 310.0,
    accountId: 'acc-002',
    accountName: 'Main Office Petty Cash Drawer',
    paymentMethod: 'cash',
    vendor: 'Speedy Express Dispatch',
    description: 'Local expedited courier delivery to aerospace client',
    expenseStatus: 'posted',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'exp-004',
    tenantId: 'tenant-apex-corp',
    expenseNumber: 'EXP-3004',
    category: 'Marketing & Advertising',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    amount: 650.0,
    taxAmount: 0,
    totalAmount: 650.0,
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'credit_card',
    vendor: 'LinkedIn B2B Advertising',
    description: 'Q3 Enterprise Lead Generation Campaign for aerospace clients',
    expenseStatus: 'posted',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'exp-005',
    tenantId: 'tenant-apex-corp',
    expenseNumber: 'EXP-3005',
    category: 'Utilities & Power',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    amount: 890.0,
    taxAmount: 73.43,
    totalAmount: 963.43,
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'bank_transfer',
    vendor: 'Austin Energy & High Voltage Power',
    description: 'Monthly industrial facility three-phase power consumption',
    expenseStatus: 'posted',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'exp-006',
    tenantId: 'tenant-apex-corp',
    expenseNumber: 'EXP-3006-DRAFT',
    category: 'Office Supplies & Admin',
    date: new Date().toISOString(),
    amount: 145.0,
    taxAmount: 0,
    totalAmount: 145.0,
    accountId: 'acc-002',
    accountName: 'Main Office Petty Cash Drawer',
    paymentMethod: 'cash',
    vendor: 'Office Depot Warehouse',
    description: 'Quarterly printer ink cartridges and thermal receipt rolls [DRAFT]',
    expenseStatus: 'draft',
    status: 'active',
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'exp-007',
    tenantId: 'tenant-apex-corp',
    expenseNumber: 'EXP-3007-VOID',
    category: 'Logistics & Fuel',
    date: new Date(Date.now() - 8 * 86400000).toISOString(),
    amount: 220.0,
    taxAmount: 0,
    totalAmount: 220.0,
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'bank_transfer',
    vendor: 'Wrong Freight Courier Co.',
    description: 'Duplicate delivery charge reversal [CANCELLED/VOID]',
    expenseStatus: 'void',
    voidReason: 'Invoice duplicate submitted by contractor; funds reversed to account',
    voidDate: new Date(Date.now() - 7 * 86400000).toISOString(),
    status: 'inactive',
    isDeleted: false,
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    tenantId: 'tenant-apex-corp',
    paymentNumber: 'RCPT-1001',
    partyType: 'customer',
    partyId: 'cust-001',
    partyName: 'Vanguard Aerospace Inc. [DEMO SEED DATA]',
    type: 'receipt',
    amount: 5000.0,
    date: new Date(Date.now() - 10 * 86400000).toISOString(),
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'bank_transfer',
    reference: 'WIRE-99281920',
    notes: 'Advance installment towards Q3 hydraulic systems batch [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'pay-002',
    tenantId: 'tenant-apex-corp',
    paymentNumber: 'PMT-2001',
    partyType: 'supplier',
    partyId: 'supp-001',
    partyName: 'Precision Hydraulics Manufacturing [DEMO SEED DATA]',
    type: 'payment',
    amount: 1000.0,
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'bank_transfer',
    reference: 'ACH-4820194',
    notes: 'Partial settlement for PO-2002 filter inventory [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'pay-003',
    tenantId: 'tenant-apex-corp',
    paymentNumber: 'RCPT-1002',
    partyType: 'customer',
    partyId: 'cust-002',
    partyName: 'Summit Logistics Ltd. [DEMO SEED DATA]',
    type: 'receipt',
    amount: 1200.0,
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    accountId: 'acc-002',
    accountName: 'Main Office Petty Cash Drawer',
    paymentMethod: 'cash',
    reference: 'RCPT-CASH-402',
    notes: 'Counter deposit for transport spare units [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'pay-004',
    tenantId: 'tenant-apex-corp',
    paymentNumber: 'RCPT-1003',
    partyType: 'customer',
    partyId: 'cust-004',
    partyName: 'Quantum Robotics Labs [DEMO SEED DATA]',
    type: 'receipt',
    amount: 250.0,
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'bank_transfer',
    reference: 'WIRE-QR-502',
    notes: 'Advance deposit for INV-1005 thermal imaging unit [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'pay-005',
    tenantId: 'tenant-apex-corp',
    paymentNumber: 'PMT-2002',
    partyType: 'supplier',
    partyId: 'supp-002',
    partyName: 'AeroTech Fasteners & Alloys [DEMO SEED DATA]',
    type: 'payment',
    amount: 1800.0,
    date: new Date(Date.now() - 6 * 86400000).toISOString(),
    accountId: 'acc-001',
    accountName: 'Bank of America — Primary Operating',
    paymentMethod: 'bank_transfer',
    reference: 'ACH-AT-8812',
    notes: 'Full settlement for PO-2003 filter batch delivery [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'pay-006',
    tenantId: 'tenant-apex-corp',
    paymentNumber: 'PMT-2003',
    partyType: 'supplier',
    partyId: 'supp-005',
    partyName: 'Global Packaging & Crating [DEMO SEED DATA]',
    type: 'payment',
    amount: 3400.0,
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    accountId: 'acc-003',
    accountName: 'JPMorgan Chase — Commercial Reserve',
    paymentMethod: 'bank_transfer',
    reference: 'CHASE-WIRE-99201',
    notes: '50% upfront deposit on PO-2005 industrial crates [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-001',
    tenantId: 'tenant-apex-corp',
    name: 'Heavy Machinery [DEMO SEED DATA]',
    code: 'CAT-MACH',
    description: 'Pumps, actuators, industrial motors, and heavy drive assemblies.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-002',
    tenantId: 'tenant-apex-corp',
    name: 'Filtration [DEMO SEED DATA]',
    code: 'CAT-FLTR',
    description: 'Carbon cartridges, micro-pore screens, and hydraulic fluid filters.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-003',
    tenantId: 'tenant-apex-corp',
    name: 'Electronics [DEMO SEED DATA]',
    code: 'CAT-ELEC',
    description: 'Thermal sensors, telemetry modules, microcontrollers, and wiring harnesses.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-004',
    tenantId: 'tenant-apex-corp',
    name: 'Valves & Fittings [DEMO SEED DATA]',
    code: 'CAT-VALV',
    description: 'Solenoid valves, brass connectors, and high-pressure pipe fittings.',
    status: 'inactive',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-005',
    tenantId: 'tenant-apex-corp',
    name: 'Industrial Polymers [DEMO SEED DATA]',
    code: 'CAT-POLY',
    description: 'High-temperature seals, gaskets, and chemical-resistant tubing.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-exp-001',
    tenantId: 'tenant-apex-corp',
    name: 'Facility & Rent',
    code: 'EXP-RENT',
    description: 'Commercial facilities, leases, warehouse rents, and property occupancy fees.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-exp-002',
    tenantId: 'tenant-apex-corp',
    name: 'Cloud & Infrastructure',
    code: 'EXP-CLOUD',
    description: 'Cloud hosting, SaaS subscriptions, servers, and digital IT services.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-exp-003',
    tenantId: 'tenant-apex-corp',
    name: 'Logistics & Fuel',
    code: 'EXP-LOGIS',
    description: 'Fleet transport fuel, freight forwarding, dispatch, and delivery postage.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-exp-004',
    tenantId: 'tenant-apex-corp',
    name: 'Marketing & Advertising',
    code: 'EXP-MKTG',
    description: 'Digital campaigns, lead generation, trade show booths, and brand collateral.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-exp-005',
    tenantId: 'tenant-apex-corp',
    name: 'Utilities & Power',
    code: 'EXP-UTIL',
    description: 'Electricity, commercial three-phase power, water, and waste management.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'cat-exp-006',
    tenantId: 'tenant-apex-corp',
    name: 'Office Supplies & Admin',
    code: 'EXP-OFFC',
    description: 'Stationery, paper, toner, consumables, and general administrative needs.',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_STOCK_TRANSACTIONS: StockTransaction[] = [
  // prod-001 (Hydraulic Pump): 41 initial + 5 PO - 4 INV = 42
  {
    id: 'stk-001',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-001',
    productName: 'Industrial Grade Hydraulic Pump H-400',
    sku: 'PUMP-HYD-400',
    quantity: 41,
    direction: 'in',
    type: 'initial_stock',
    reference: 'INIT-STOCK-001',
    referenceType: 'initial',
    date: new Date(Date.now() - 30 * 86400000).toISOString(),
    cost: 850.0,
    totalCost: 34850.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Initial inventory audit balance [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-002',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-001',
    productName: 'Industrial Grade Hydraulic Pump H-400',
    sku: 'PUMP-HYD-400',
    quantity: 5,
    direction: 'in',
    type: 'purchase',
    reference: 'PO-2001',
    referenceType: 'purchase',
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    cost: 850.0,
    totalCost: 4250.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Warehouse batch shipment received from Acme [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-003',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-001',
    productName: 'Industrial Grade Hydraulic Pump H-400',
    sku: 'PUMP-HYD-400',
    quantity: 4,
    direction: 'out',
    type: 'sale',
    reference: 'INV-1001',
    referenceType: 'sale',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    cost: 850.0,
    totalCost: 3400.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Dispatched for Vanguard Aerospace delivery [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // prod-002 (Filter Cartridge): 90 initial + 50 PO - 20 INV = 120
  {
    id: 'stk-004',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-002',
    productName: 'Reinforced Carbon Filter Cartridge 20"',
    sku: 'FLTR-CRB-020',
    quantity: 90,
    direction: 'in',
    type: 'initial_stock',
    reference: 'INIT-STOCK-002',
    referenceType: 'initial',
    date: new Date(Date.now() - 30 * 86400000).toISOString(),
    cost: 45.0,
    totalCost: 4050.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Initial inventory audit balance [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-005',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-002',
    productName: 'Reinforced Carbon Filter Cartridge 20"',
    sku: 'FLTR-CRB-020',
    quantity: 50,
    direction: 'in',
    type: 'purchase',
    reference: 'PO-2002',
    referenceType: 'purchase',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    cost: 45.0,
    totalCost: 2250.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Supplier replenishment batch [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-006',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-002',
    productName: 'Reinforced Carbon Filter Cartridge 20"',
    sku: 'FLTR-CRB-020',
    quantity: 20,
    direction: 'out',
    type: 'sale',
    reference: 'INV-1002',
    referenceType: 'sale',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    cost: 45.0,
    totalCost: 900.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Consignment delivery to Summit Logistics [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // prod-003 (Sensor Module): 8 initial - 2 INV = 6 (Low Stock!)
  {
    id: 'stk-007',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-003',
    productName: 'Thermal Imaging Sensor Module T-90',
    sku: 'SNSR-THM-090',
    quantity: 8,
    direction: 'in',
    type: 'initial_stock',
    reference: 'INIT-STOCK-003',
    referenceType: 'initial',
    date: new Date(Date.now() - 20 * 86400000).toISOString(),
    cost: 220.0,
    totalCost: 1760.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Initial inventory audit balance [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-008',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-003',
    productName: 'Thermal Imaging Sensor Module T-90',
    sku: 'SNSR-THM-090',
    quantity: 2,
    direction: 'out',
    type: 'sale',
    reference: 'INV-1003',
    referenceType: 'sale',
    date: new Date().toISOString(),
    cost: 220.0,
    totalCost: 440.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Fulfilled on order INV-1003 [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // prod-004 (Discontinued Valve): 10 initial - 10 adjustment_out = 0
  {
    id: 'stk-009',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-004',
    productName: 'Legacy Solenoid Valve 1/2" NPT (Discontinued)',
    sku: 'VALV-SLN-050-D',
    quantity: 10,
    direction: 'in',
    type: 'initial_stock',
    reference: 'INIT-STOCK-004',
    referenceType: 'initial',
    date: new Date(Date.now() - 80 * 86400000).toISOString(),
    cost: 32.0,
    totalCost: 320.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Initial inventory opening balance [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 80 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-010',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-004',
    productName: 'Legacy Solenoid Valve 1/2" NPT (Discontinued)',
    sku: 'VALV-SLN-050-D',
    quantity: 10,
    direction: 'out',
    type: 'adjustment_out',
    reference: 'ADJ-WO-001',
    referenceType: 'stock_adjustment',
    date: new Date(Date.now() - 40 * 86400000).toISOString(),
    cost: 32.0,
    totalCost: 320.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Discontinued product lines written off and cleared [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },

  // prod-005 (Nexus Tech): 85 initial = 85
  {
    id: 'stk-011',
    tenantId: 'tenant-nexus-tech',
    productId: 'prod-005',
    productName: 'Optical Network Transceiver 100G QSFP28',
    sku: 'OPT-QSFP-100G',
    quantity: 85,
    direction: 'in',
    type: 'initial_stock',
    reference: 'INIT-STOCK-005',
    referenceType: 'initial',
    date: new Date(Date.now() - 10 * 86400000).toISOString(),
    cost: 310.0,
    totalCost: 26350.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Initial optical fiber transceiver stock [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-012',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-002',
    productName: 'Reinforced Carbon Filter Cartridge 20"',
    sku: 'FLTR-CRB-020',
    quantity: 40,
    direction: 'in',
    type: 'purchase',
    reference: 'PO-2003',
    referenceType: 'purchase',
    date: new Date(Date.now() - 6 * 86400000).toISOString(),
    cost: 45.0,
    totalCost: 1800.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Received via PO-2003 [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-013',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-003',
    productName: 'Thermal Imaging Sensor Module T-90',
    sku: 'SNSR-THM-090',
    quantity: 10,
    direction: 'in',
    type: 'purchase',
    reference: 'PO-2004',
    referenceType: 'purchase',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    cost: 220.0,
    totalCost: 2200.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Received via PO-2004 [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-014',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-002',
    productName: 'Reinforced Carbon Filter Cartridge 20"',
    sku: 'FLTR-CRB-020',
    quantity: 30,
    direction: 'out',
    type: 'sale',
    reference: 'INV-1004',
    referenceType: 'sale',
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    cost: 45.0,
    totalCost: 1350.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Sold via Invoice INV-1004 [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'stk-015',
    tenantId: 'tenant-apex-corp',
    productId: 'prod-003',
    productName: 'Thermal Imaging Sensor Module T-90',
    sku: 'SNSR-THM-090',
    quantity: 1,
    direction: 'out',
    type: 'sale',
    reference: 'INV-1005',
    referenceType: 'sale',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    cost: 220.0,
    totalCost: 220.0,
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    notes: 'Sold via Invoice INV-1005 [DEMO SEED DATA]',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'je-001',
    tenantId: 'tenant-apex-corp',
    entryNumber: 'JE-10001',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    reference: 'INV-1001',
    description: 'Commercial Sale: Vanguard Aerospace Inc. (Inv #INV-1001)',
    sourceModule: 'sales',
    sourceId: 'inv-001',
    sourceNumber: 'INV-1001',
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    status: 'posted',
    isDeleted: false,
    isBalanced: true,
    totalDebit: 9675.0,
    totalCredit: 9675.0,
    lines: [
      {
        id: 'jel-001-1',
        accountId: 'acc-1100',
        accountNumber: '1100-AR-CONTROL',
        accountName: 'Accounts Receivable Control (Trade Debtors)',
        accountType: 'accounts_receivable',
        debit: 4800.0,
        credit: 0,
        description: 'Customer outstanding balance on INV-1001',
      },
      {
        id: 'jel-001-2',
        accountId: 'acc-001',
        accountNumber: '1010-BOA-OPERATING',
        accountName: 'Bank of America — Primary Operating',
        accountType: 'bank',
        debit: 1475.0,
        credit: 0,
        description: 'Upfront deposit received on INV-1001',
      },
      {
        id: 'jel-001-3',
        accountId: 'acc-4010',
        accountNumber: '4010-SALES-REVENUE',
        accountName: 'Commercial Sales Revenue',
        accountType: 'income',
        debit: 0,
        credit: 5800.0,
        description: 'Gross sales revenue on INV-1001',
      },
      {
        id: 'jel-001-4',
        accountId: 'acc-2050',
        accountNumber: '2050-TAX-PAYABLE',
        accountName: 'Sales Tax & VAT Payable',
        accountType: 'liability',
        debit: 0,
        credit: 475.0,
        description: 'Sales tax collected on INV-1001',
      },
      {
        id: 'jel-001-5',
        accountId: 'acc-5010',
        accountNumber: '5010-COGS-WHOLESALE',
        accountName: 'Cost of Goods Sold (COGS) — Wholesale',
        accountType: 'cogs',
        debit: 3400.0,
        credit: 0,
        description: 'Inventory cost of goods dispatched on INV-1001',
      },
      {
        id: 'jel-001-6',
        accountId: 'acc-1200',
        accountNumber: '1200-INV-MERCH',
        accountName: 'Merchandise Inventory Stock Asset',
        accountType: 'inventory',
        debit: 0,
        credit: 3400.0,
        description: 'Inventory reduction for sold hydraulic pumps',
      },
    ],
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'je-002',
    tenantId: 'tenant-apex-corp',
    entryNumber: 'JE-10002',
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    reference: 'PO-2001',
    description: 'Procurement Order: Precision Hydraulics Mfg (PO #PO-2001)',
    sourceModule: 'purchases',
    sourceId: 'po-001',
    sourceNumber: 'PO-2001',
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    status: 'posted',
    isDeleted: false,
    isBalanced: true,
    totalDebit: 8500.0,
    totalCredit: 8500.0,
    lines: [
      {
        id: 'jel-002-1',
        accountId: 'acc-1200',
        accountNumber: '1200-INV-MERCH',
        accountName: 'Merchandise Inventory Stock Asset',
        accountType: 'inventory',
        debit: 8500.0,
        credit: 0,
        description: 'Purchased inventory stock delivered on PO-2001',
      },
      {
        id: 'jel-002-2',
        accountId: 'acc-2010',
        accountNumber: '2010-AP-CONTROL',
        accountName: 'Accounts Payable Control (Trade Creditors)',
        accountType: 'accounts_payable',
        debit: 0,
        credit: 6500.0,
        description: 'Supplier balance payable to Precision Hydraulics',
      },
      {
        id: 'jel-002-3',
        accountId: 'acc-001',
        accountNumber: '1010-BOA-OPERATING',
        accountName: 'Bank of America — Primary Operating',
        accountType: 'bank',
        debit: 0,
        credit: 2000.0,
        description: 'Initial supplier advance wire payment',
      },
    ],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'je-003',
    tenantId: 'tenant-apex-corp',
    entryNumber: 'JE-10003',
    date: new Date(Date.now() - 10 * 86400000).toISOString(),
    reference: 'RCPT-1001',
    description: 'Customer Payment Received: Vanguard Aerospace (RCPT-1001)',
    sourceModule: 'payments',
    sourceId: 'pay-001',
    sourceNumber: 'RCPT-1001',
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    status: 'posted',
    isDeleted: false,
    isBalanced: true,
    totalDebit: 5000.0,
    totalCredit: 5000.0,
    lines: [
      {
        id: 'jel-003-1',
        accountId: 'acc-001',
        accountNumber: '1010-BOA-OPERATING',
        accountName: 'Bank of America — Primary Operating',
        accountType: 'bank',
        debit: 5000.0,
        credit: 0,
        description: 'Bank receipt deposit from customer wire transfer',
      },
      {
        id: 'jel-003-2',
        accountId: 'acc-1100',
        accountNumber: '1100-AR-CONTROL',
        accountName: 'Accounts Receivable Control (Trade Debtors)',
        accountType: 'accounts_receivable',
        debit: 0,
        credit: 5000.0,
        description: 'Reduction of customer receivables ledger balance',
      },
    ],
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'je-004',
    tenantId: 'tenant-apex-corp',
    entryNumber: 'JE-10004',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    reference: 'EXP-3001',
    description: 'Operating Expense: Austin Industrial Park Holdings (EXP-3001)',
    sourceModule: 'expenses',
    sourceId: 'exp-001',
    sourceNumber: 'EXP-3001',
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    status: 'posted',
    isDeleted: false,
    isBalanced: true,
    totalDebit: 1850.0,
    totalCredit: 1850.0,
    lines: [
      {
        id: 'jel-004-1',
        accountId: 'acc-6010',
        accountNumber: '6010-EXP-FACILITY',
        accountName: 'Facility Lease & Warehouse Expenses',
        accountType: 'expense',
        debit: 1850.0,
        credit: 0,
        description: 'Monthly industrial facility lease disbursement',
      },
      {
        id: 'jel-004-2',
        accountId: 'acc-001',
        accountNumber: '1010-BOA-OPERATING',
        accountName: 'Bank of America — Primary Operating',
        accountType: 'bank',
        debit: 0,
        credit: 1850.0,
        description: 'Disbursement from primary operational checking',
      },
    ],
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'je-005',
    tenantId: 'tenant-apex-corp',
    entryNumber: 'JE-10005',
    date: new Date(Date.now() - 6 * 86400000).toISOString(),
    reference: 'PMT-2002',
    description: 'Supplier Payment: AeroTech Fasteners & Alloys (PMT-2002)',
    sourceModule: 'payments',
    sourceId: 'pay-005',
    sourceNumber: 'PMT-2002',
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    status: 'posted',
    isDeleted: false,
    isBalanced: true,
    totalDebit: 1800.0,
    totalCredit: 1800.0,
    lines: [
      {
        id: 'jel-005-1',
        accountId: 'acc-2010',
        accountNumber: '2010-AP-CONTROL',
        accountName: 'Accounts Payable Control (Trade Creditors)',
        accountType: 'accounts_payable',
        debit: 1800.0,
        credit: 0,
        description: 'Settlement payment towards supplier balance on PO-2003',
      },
      {
        id: 'jel-005-2',
        accountId: 'acc-001',
        accountNumber: '1010-BOA-OPERATING',
        accountName: 'Bank of America — Primary Operating',
        accountType: 'bank',
        debit: 0,
        credit: 1800.0,
        description: 'Wire disbursement from Bank of America operating',
      },
    ],
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'je-006',
    tenantId: 'tenant-apex-corp',
    entryNumber: 'JE-10006',
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    reference: 'EXP-3003',
    description: 'Operating Expense: Speedy Express Dispatch (EXP-3003)',
    sourceModule: 'expenses',
    sourceId: 'exp-003',
    sourceNumber: 'EXP-3003',
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    status: 'posted',
    isDeleted: false,
    isBalanced: true,
    totalDebit: 310.0,
    totalCredit: 310.0,
    lines: [
      {
        id: 'jel-006-1',
        accountId: 'acc-6030',
        accountNumber: '6030-EXP-LOGISTICS',
        accountName: 'Freight, Logistics & Fuel Expenses',
        accountType: 'expense',
        debit: 310.0,
        credit: 0,
        description: 'Expedited client freight courier delivery charge',
      },
      {
        id: 'jel-006-2',
        accountId: 'acc-002',
        accountNumber: '1020-PETTY-CASH',
        accountName: 'Main Office Petty Cash Drawer',
        accountType: 'cash',
        debit: 0,
        credit: 310.0,
        description: 'Cash payment from physical drawer till',
      },
    ],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
  {
    id: 'je-007',
    tenantId: 'tenant-apex-corp',
    entryNumber: 'JE-10007-REV',
    date: new Date(Date.now() - 7 * 86400000).toISOString(),
    reference: 'EXP-3007-VOID',
    description: 'Reversal Entry: Void duplicate freight disbursement (EXP-3007)',
    sourceModule: 'cancellation',
    sourceId: 'exp-007',
    sourceNumber: 'EXP-3007',
    userId: 'user-default-admin',
    userName: 'Chief Administrator',
    status: 'posted',
    isDeleted: false,
    reversalReason: 'Duplicate invoice submitted by courier contractor; full accounting reversal posted',
    isBalanced: true,
    totalDebit: 220.0,
    totalCredit: 220.0,
    lines: [
      {
        id: 'jel-007-1',
        accountId: 'acc-001',
        accountNumber: '1010-BOA-OPERATING',
        accountName: 'Bank of America — Primary Operating',
        accountType: 'bank',
        debit: 220.0,
        credit: 0,
        description: 'Restoration of funds to primary operating checking account',
      },
      {
        id: 'jel-007-2',
        accountId: 'acc-6030',
        accountNumber: '6030-EXP-LOGISTICS',
        accountName: 'Freight, Logistics & Fuel Expenses',
        accountType: 'expense',
        debit: 0,
        credit: 220.0,
        description: 'Counter-balancing credit reversing expense from operating overhead',
      },
    ],
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: 'user-default-admin',
    updatedBy: 'user-default-admin',
  },
];
